<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IABLR-LT155" name="timeoutpackage.Admin" tests="3" failures="0" timestamp="2 Apr 2020 11:50:52 GMT" time="9.023" errors="1">
  <testcase name="test3" time="2.005" classname="timeoutpackage.Admin"/>
  <testcase name="test1" time="5.013" classname="timeoutpackage.Admin">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.test1() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.test1() didn't finish within the time-out 5000
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- test1 -->
  <testcase name="test4" time="2.005" classname="timeoutpackage.Admin"/>
</testsuite> <!-- timeoutpackage.Admin -->
